export const SET_LOADING = "SET_LOADING"
export const SET_STORY = "SET_STORY"
export const REMOVE_STORY = "REMOVE_STORY"
export const HANDLE_PAGE = "HANDLE_PAGE"
export const HANDLE_QUERY = "HANDLE_QUERY"